typography_spectrum: 0.114984787767753
color:
  brandColors:
    - '#08080a'
    - '#514245'
    - '#7e6d42'
    - '#bca6b2'
    - '#e6d3d9'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7074943836778402
analytics:
  google: null
  facebook: null
  twitter: null
name: NatoNoel
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Nato's News
description: All the latest from Nathanael
purpose: []
