name: NatoNoel
favicon: null
layout_spectrum: 0.7074943836778402
typography_spectrum: 0.114984787767753
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1349968931172043
  lightness: 0.7866950365714729
  saturation: 0.08018164779059589
  rhythmicContrast: 0.15987448091618717
purpose: []
